#import "../utils/template.typ": *
#import "../bib_state.typ": bib_state
#context bib_state.get()



== The toric code
<toric-code>
Toric code are essentially the definition of logical qubits on a periodic lattice (a torus) of physical qubits through the topological properties arising from the definition of two special operators.~@Kitaev_2003[!] introduced the concept. Let us define the plaquette and vertex operators.

$
  A_p & = sum_(i in +_p) Z_i \
  B_k & = sum_(i in square.stroked_k) X_k
$

where $+_p$ is the set of operators acting on the edges around a vertex
$v_p$ (the four ends of the cross), whereas $square.stroked_k$
contains operators centered on a face $f_k$, acting on its four edges. These two operators always commute, since the number of overlapping vertices is always even.


#include "../files/cetz/toricgrid.typ"


Consider the Hamiltonian; $ H = - sum_p A_p - sum_k B_k $ It has four distinct degenerate ground states: the entirely spin 0 state $S_0$, also known as the "loop vacuum", which includes any loop that doesn't wind around the boundary, since it can be deformed using $B$ back to the vacuum.

#include "../files/cetz/deformstring.typ"

The three other group are the vertically winding string, $S_v$, the horizontal string, $S_h$, and their sum $S_S$. Each group is linearly independent with respect tot the $A$ and $B$ operators.


#include "../files/cetz/toricgroundstate.typ"

These four ground states are generated by winding Pauli strings.

If we identify each group with a state, 
$
 S_0 & = ket(00) \
      S_h & = ket(10) \
            S_v & = ket(01) \
                  S_s & = ket(11). $

we may switch from a two-qubit state to another, by applying a vertical string, either $X_v$ or $Z_v$, or a horizontal string, either $X_h$ or
$Z_h$. 
$
 X_h ket(00) & = ket(10) = tilde(X)_1 ket(00) \
Z_v ket(10) & = -ket(10) = tilde(Z)_1 ket(10) \
X_v ket(00) & = ket(01) = tilde(X)_2 ket(00) \
Z_h ket(01) & = -ket(01) = tilde(Z)_2 ket(01) 
$

We then have two qubits encoded in this lattice, which are protected against any stabilizer operation. More formally, there exists a protected subspace $cal(L)$ of dimension 4:

$
  cal(V) := {ket(xi): A_p ket(xi) = ket(xi), B_k ket(xi) = ket(xi), forall p,k}
$

In this protected subspace, any undesired $A_p$ pr $B_k$ applied to the system leaves it invariant. We may, however, create abelian anyonic excitations with string operators $S^z$ and $S^x$, which would break the invariance:

$
  S^z ( t ) & = sum_(j in t) Z_j \
              S^z ( t' ) & = sum_(j in t') X_j
$

where $t$ and $t'$ are non-closed paths ("strings") on the lattice. Two particles are created, one at each end of the string. $Z$ particles are called #emph[electric charges] and $X$ particles #emph[magnetic
  vortices].
